// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechNation.Desafio.Infra.Context;

#nullable disable

namespace TechNation.Desafio.Infra.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20240817172237_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechNation.Desafio.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCobranca")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentoBoletoBancario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoNotaFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdStatusNotaFiscal")
                        .HasColumnType("int");

                    b.Property<string>("NomePagador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroIdentificacao")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasAnnotation("RegularExpression", "^[0-9]{6}$");

                    b.Property<int?>("StatusNotaFiscalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdStatusNotaFiscal");

                    b.HasIndex("StatusNotaFiscalId");

                    b.ToTable("NotaFiscal");
                });

            modelBuilder.Entity("TechNation.Desafio.Domain.Entities.StatusNotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusNotaFiscal");
                });

            modelBuilder.Entity("TechNation.Desafio.Domain.Entities.NotaFiscal", b =>
                {
                    b.HasOne("TechNation.Desafio.Domain.Entities.StatusNotaFiscal", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("IdStatusNotaFiscal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNation.Desafio.Domain.Entities.StatusNotaFiscal", "StatusNotaFiscal")
                        .WithMany()
                        .HasForeignKey("StatusNotaFiscalId");

                    b.Navigation("StatusNotaFiscal");
                });

            modelBuilder.Entity("TechNation.Desafio.Domain.Entities.StatusNotaFiscal", b =>
                {
                    b.Navigation("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
