services:
  technation.desafio.api:
    image: ${DOCKER_REGISTRY:-technationdesafioapi}
    build:
      context: .
      dockerfile: src/TechNation.Desafio.API/Dockerfile
    ports:
      - "4237:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__TechNationContextConnection: "Server=sqlserver;Database=TechNation.Desafio;User Id=sa;Password=technation@123;TrustServerCertificate=True;"

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "technation@123"
